pipeline {
agent any
triggers {
    githubPush()
}
stages {
    stage('Restore packages'){
        steps{
            sh 'dotnet restore TodoApp.sln'
        }
    }
    stage('Clean'){
        steps{
            sh 'dotnet clean TodoApp.sln --configuration Release'
        }
    }
    stage('Build'){
        steps{
            sh 'dotnet build TodoApp.sln --configuration Release --no-restore'
        }
    }
    stage('Publish'){
        steps{
            sh 'dotnet publish TodoApp/TodoApp.csproj --configuration Release --no-restore'
        }
    }
    stage('Deploy'){
        steps{
            sh '''for pid in $(lsof -t -i:9090); do
                kill -9 $pid
                done'''
            sh 'cd TodoApp/bin/Release/netcoreapp3.1/publish/'
            sh 'nohup dotnet TodoApp.dll --urls="SECRET" --ip="SECRET" --port=9090 --no-restore > /dev/null 2>&1 &'
        }
    }
}
}